name = "utils"
main = "src/worker.js"
compatibility_date = "2024-11-14"
workers_dev = false
preview_urls = false

[placement]
mode = "smart"

[observability]
enabled = false

  [observability.logs]
  enabled = true
  head_sampling_rate = 1
  invocation_logs = true
